version: 2.1
orbs:
  # "cypress-io/cypress@3" installs the latest published
  # version "s.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@3.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@3.3.1

jobs:
  cypress-run:
    executor:
      name: cypress/default
      node-version: '18.17.0'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start server and run tests
          command:
            npm run dev &  # 서버를 백그라운드에서 실행
            # 서버가 준비될 때까지 대기
            until $(curl --output /dev/null --silent --head --fail http://localhost:3000); do
              printf '.'
              sleep 1
            done
            # Cypress 테스트 실행
            npx cypress run --component --parallel --record
workflows:
  build:
    jobs:
      - cypress-run
